### ISSUE TITLE
Accept leeway while checking expiration

### ISSUE THREAD

**Issue by RockyMM** [FusionAuth/fusionauth-jwt#12]
In some use cases it would be beneficial to allow for a small leeway when checking whether a token has expired, to account for clock differences in client and server machines.

Simple&dirty way could be to overload `decode` method.

Nicer way would be to extend Verifier with optional `leeway` parameter in seconds and to use this parameter in the `Decoder` and to move expiration responsibility to `Decoder`.

**Comment by robotdan** [comment]
This is a good idea. I know most SAML libraries have a default skew of a few minutes that can be configured. Coming soon.

**Comment by jarekratajski** [comment]
See pull request #25

**Comment by robotdan** [comment]
Messing with this solution to see how it feels: https://github.com/FusionAuth/fusionauth-jwt/commit/e1adc64fac959d5f230af28b80a7c050e9b59b7c

**Comment by robotdan** [comment]
@RockyMM @jarekratajski and I have been working on a solution. Let me know if you have any opinion, see example options 1, 2 and 3 : https://github.com/FusionAuth/fusionauth-jwt/pull/25#issuecomment-719170777

**Comment by robotdan** [comment]
This is available in version 3.6.0. Use `withClockSkew` on the JWT Decoder, defaults to `0`.
