### ISSUE TITLE
Extend HMACSigner to accept byte[] as secret input

### ISSUE THREAD

**Issue by sadovnyc** [FusionAuth/fusionauth-jwt#15]
Hi, there is no api which allows creating HMACSigner from byte[], even though HMAC signer constructor will convert String to byte[].
As well, it is incompatible with HMACVerifier which accepts byte[] as input.
So now, to create HMACSigner from byte[] , I need to redefine the whole class.

**Comment by robotdan** [comment]
Added some additional methods in commit 
https://github.com/FusionAuth/fusionauth-jwt/commit/348130302919739024794bde59f9db21ddf93f86

**Comment by sadovnyc** [comment]
Thanks, a lot for fast fix. I've migrated to 3.2.0, it works.
