### ISSUE TITLE
How to use JSONWebKey to create a JWT token?

### ISSUE THREAD

**Issue by devnewton** [FusionAuth/fusionauth-jwt#16]

**Comment by robotdan** [comment]
Can you provide some more context of what you're trying to accomplish? Are you looking to sign a token with a private key from a JSON Web Key, or validate a token with the public key from a JSON Web Key?

**Comment by devnewton** [comment]
I would like to use a jwks (like those generated by https://mkjwk.org/) to sign/encrypt a token.

**Comment by robotdan** [comment]
This is already possible. Please review the README and find `Extract the Public Key from a JWK`.

**Comment by robotdan** [comment]
Did you still have questions on this, or can we close out the issue?
