### ISSUE TITLE
Support JWT Fingerprints

### ISSUE THREAD

**Issue by jamietanna** [FusionAuth/fusionauth-jwt#18]
[RFC7638 _JSON Web Key (JWK) Thumbprint_](https://tools.ietf.org/html/rfc7638) describes a standard method to generate the `kid` field for a given JSON Web Key.

This is commonly required, and given we can generate a JWK from a PEM / `PublicKey` / `PrivateKey`, we should be able to use this to generate a `kid`.

If you're interested in this feature, I'd be happy to submit a PR :smile:

**Comment by robotdan** [comment]
This should already be working. If it isn't please provide a code example.

Thanks.

**Comment by jamietanna** [comment]
The below code example fails when using [this certificate](https://keystore.openbanking.org.uk/001580000103UAQAA2/x7THoMF8N-U4q8lo4MZokJ1CxkM.pem) against v3.5.0 of this library:

```java
    CertificateFactory fact = CertificateFactory.getInstance("X.509");
    FileInputStream is =
        new FileInputStream("x7THoMF8N-U4q8lo4MZokJ1CxkM.pem");
    X509Certificate cer = (X509Certificate) fact.generateCertificate(is);
    // as a certificate
    JSONWebKey jwk = JSONWebKey.build(cer);
    assert(jwk.kid != null);
    // as a public key
    JSONWebKey jwk = JSONWebKey.build(cer.getPublicKey());
    assert(jwk.kid != null);
```

As `kid` is defaulted to `null`, and not generated.

I don't seem to be able to find any helper methods to generate this `kid` as a JWK Thumbprint, only as an X.509 Thumbprint.

**Comment by robotdan** [comment]
Ah, I see what you mean. Yes, we are not setting the `kid` automatically to the certificate thumbprint.

You can use the `JWTUtils.generateJWS_x5t` to generate the thumbprint and set it to the `kid`.  

The `kid` can be anything you want, a common choice when representing a certificate is the `x5t`.

**Comment by jamietanna** [comment]
Ah that makes sense. Would you be happy receiving a PR that adds i.e. `JWTUtils.generateJWS_thumbprint`, that follows RFC7638 to produce a `kid`?

It would be good to have this as an option in this library

**Comment by robotdan** [comment]
Ok, I think I was confused. The utility methods that we have to generate `x5t` ( X.509 Certificate Thumbprint ) values are for certificate thumbprints. You are talking more specifically about JWK thumbprints. 

Yes, then you are correct. We are not generating JWT thumbprints, and do not have any utility methods to generate them. 

If you would like to submit a PR I will review it.
