### ISSUE TITLE
Add support for OAuth2 configuration

### ISSUE THREAD

**Issue by jamietanna** [FusionAuth/fusionauth-jwt#23]
[RFC8414 defines OAuth 2.0 Authorization Server Metadata](https://tools.ietf.org/html/rfc8414) which is the OAuth2-specific implementation of [OpenID Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html).

Would you be interested in having support for this, similar to `io.fusionauth.jwks.JSONWebKeySetHelper#retrieveKeysFromIssuer`?

**Comment by robotdan** [comment]
Seems reasonable.

**Comment by robotdan** [comment]
Is this just to add some additional tests you mean? The ones that are there should work since those are legit endpoints. 
https://github.com/FusionAuth/fusionauth-jwt/blob/48cd5897019b923ad7fe318aa0d632484a0ccddd/src/test/java/io/fusionauth/jwks/JSONWebKeySetTest.java


Or do you mean in order to add code for `retrieveKeysFromIssuer`?

**Comment by jamietanna** [comment]
Sorry, I wasn't clear. In <code>JSONWebKeySetTest</code> we're reaching out to a real set of endpoints.

However, I can't seem to find a public OAuth2 server that supports RFC8414 to write a test.

I was thinking of using something like Wiremock to create a fake server so I can stub it out, and wondered if you'd be happy with that as a change to the existing tests in <code>JSONWebKeySetTest</code>?

(Originally published at: https://www.jvt.me/mf2/2020/10/wczpu/)

**Comment by robotdan** [comment]
Ah, ok, got it. Yeah, don't have to test real endpoints if there aren't any public ones that we can hit reliably. 

You can just build some expected JSON and then parse it similar to how we do JWKS. 

https://github.com/FusionAuth/fusionauth-jwt/tree/master/src/test/resources/jwk
https://github.com/FusionAuth/fusionauth-jwt/blob/013a981b7c82173fdd40b26a0384584677aaf7f0/src/test/java/io/fusionauth/jwks/JSONWebKeyBuilderTest.java

I can help write tests as well if you know what code you want to write.

**Comment by voidmain** [comment]
If you have a valid response from that RFC, you could use the internal HTTP server that Java ships with for testing.

**Comment by robotdan** [comment]
@jamietanna I stubbed this out under https://github.com/FusionAuth/fusionauth-jwt/commit/314d76ffd3be1e433669432c93a7981258afde9b. Let me know if that will work for you.

**Comment by robotdan** [comment]
Releasing in 4.1.0, if there are additional features or missing capabilities from what I've described here, please open a new issue to track. Thanks!
