### ISSUE TITLE
Configurable timeouts on UrlConnection

### ISSUE THREAD

**Issue by alienintheheights** [FusionAuth/fusionauth-jwt#31]
## Configurable timeouts on UrlConnection
Make the timeout value for URL connections configurable, not hardcoded.

### Problem
The timeouts for connecting to endpoints are hardcoded in AbstractHttpHelper.buildURLConnection(). They are too short for our environments.

### Solution
properties or constructor based timeout options

### Alternatives/workarounds
using our own impl for JWK, but we'd rather not because we like fusionauth

### Additional context
this is especially problematic when working with various dev environments

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by robotdan** [comment]
Seems reasonable.

**Comment by robotdan** [comment]
Can you already do this? 

For example

```
JSONWebKeySetHelper.retrieveKeysFromJWKS(HttpURLConnection httpURLConnection);
```

Maybe not ideal, you'd have to build the connection object, but if you do this, you can specify any time out you like. 

Maybe we can add another method that takes a consumer so that you can modify it inline.

**Comment by robotdan** [comment]
Added some additional methods under this comment. https://github.com/FusionAuth/fusionauth-jwt/commit/baa34575d4d3651cc8cd93009b6a0f94f3ab84ab

Will this work for you? 

Example usage:

```
retrieveKeysFromJWKS("https://acme.com/jwks", connection -> connection.setConnectTimeout(5_000));

**Comment by robotdan** [comment]
4.2.0 is released.
