### ISSUE TITLE
Upgrade to Java >= 14?

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-jwt#32]
How many people would I break if I moved this to Java >= 14?

Feel free to comment on this thread. 

### Related
- https://github.com/FusionAuth/fusionauth-jwt/issues/13#issuecomment-1168946774

**Comment by Yaytay** [comment]
Fine by me.

**Comment by robotdan** [comment]
Thanks for the feedback @Yaytay. If we update the min. required version of Java, I would likely select an LTS, version 11 or 17.

**Comment by agentgt** [comment]
I was just looking at trying to use Edwards Curve and it is only supported in Java 15 or greater

https://openjdk.org/jeps/339

I have contemplated forking this project to get it since the `Algorithm` is an enum.

**Comment by mooreds** [comment]
Should probably look at java 17 now, since it is an LTS: https://www.oracle.com/news/announcement/oracle-releases-java-17-2021-09-14/

**Comment by robotdan** [comment]
There is some work in progress to make this library more modular so the base can optionally state on Java 8, and we can add support for various new algorithms using extensions. 

https://github.com/FusionAuth/fusionauth-jwt/issues/13#issuecomment-1229122878

**Comment by robotdan** [comment]
LTS versions 8, 11, 17, 21.
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Probably safe to ditch Java 8 since support is only available through extended or sustaining support from Oracle.

**Comment by robotdan** [comment]
Planning to leave the base library at Java 8 for compatibility. I don't know that there is any technical benefit to using something later. 

We could move to Java 11, to pick up a more recent LTS, but I don't know that it matters much. We should be able to release support for EDDSA w/out requiring the base library use `>= Java 17`.
