### ISSUE TITLE
Create a RSASigner.newSHA256Signer which supports PrivateKey instance

### ISSUE THREAD

**Issue by tommed** [FusionAuth/fusionauth-jwt#35]
We're using the AndroidKeyStore which protects the private exponent (by design for improved security) so it's impossible to call .getEncoded() or retrieve the private key's ASN1 for the PEM.

Your implementation is assuming this is possible, but by doing so, will only support private keys which expose the private exponent which isn't always a good idea.

Ideally rather than hard-coding the pem decoding in your RSASigner constructor, you should be accepting PrivateKey from elsewhere too and allow these to be managed by the respective KeyStore.

**Comment by robotdan** [comment]
Thanks for the request @tommed  - if I add additional methods that take a reference of type `java.security.interfaces.RSAPrivateKey` will this work for you? 

References:
https://developer.android.com/reference/java/security/KeyStore.PrivateKeyEntry
https://developer.android.com/reference/java/security/PrivateKey

**Comment by robotdan** [comment]
new methods for RSA and RSA PSS Signers -> https://github.com/FusionAuth/fusionauth-jwt/commit/b2224de9de911fea7ac132aa07456dcac74da759

**Comment by robotdan** [comment]
Available in 4.3.0
