### ISSUE TITLE
Will Grant Negotiation and Authorization Protocol (GNAP) working code be made available soon?

### ISSUE THREAD

**Issue by nathanawmk** [FusionAuth/fusionauth-jwt#37]
Will Grant Negotiation and Authorization Protocol (GNAP) working code be made available soon?

**Comment by mooreds** [comment]
@nathanawmk right now it is not on our roadmap. 

Here's our roadmap guidance: https://fusionauth.io/docs/v1/tech/core-concepts/roadmap/

Here's a tracking issue, feel free to vote this implementation work up: https://github.com/FusionAuth/fusionauth-issues/issues/1401

**Comment by mooreds** [comment]
I'm going to close this issue out since this isn't related to this repo.
