### ISSUE TITLE
Decode expired JWT throws Exception

### ISSUE THREAD

**Issue by m-Farman** [FusionAuth/fusionauth-jwt#44]
I want to verify an old expired JWT and use the JWT object for some processing.
But currently decode throw an `JWTExpiredException`  when I try to decode old JWT string.
My use case is just to verify the JWT string and get back the JWT object without throwing an exception.

**Comment by robotdan** [comment]
You could use the Time Machine Decoder.
- https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/java.client.ftl

Or you can bypass all security and just decode it using the JWT Utils. 
- https://github.com/FusionAuth/fusionauth-jwt/blob/9dca1a3757980fbd14b7118d7f3b39a7aa3ba4b2/src/main/java/io/fusionauth/jwt/JWTUtils.java#L101

Assuming one of those options will work for you?

**Comment by robotdan** [comment]
Please re-open if one of these options didn't work for you.
