### ISSUE TITLE
Best way to pull out "kid" to pick verifier?

### ISSUE THREAD

**Issue by agentgt** [FusionAuth/fusionauth-jwt#46]
I have a feeling I might be doing this wrong.

How do decode a JWT by using its "kid"?

Right now it looks like I use JWTUtils#decodeHeader to get the "kid" before using the Decoder. Then from that I can get the correct PublicKey (jwks) to pass to the decoder.

Or I can make a custom Verifier that again will probably call JWTUtils#decodeHeader.

It seems like this should be kind of built in.

**Comment by robotdan** [comment]
The decode method can handle this for you. 

Take a look at 

https://github.com/FusionAuth/fusionauth-jwt/blob/05bd82e4442c2ec4b9d7a637275b020ef38695b2/src/main/java/io/fusionauth/jwt/JWTDecoder.java#L89

Or


https://github.com/FusionAuth/fusionauth-jwt/blob/05bd82e4442c2ec4b9d7a637275b020ef38695b2/src/main/java/io/fusionauth/jwt/JWTDecoder.java#L106

**Comment by agentgt** [comment]
I must have been looking at an older version of the code or I just completely missed that! Either that or some IDE cache issue as I tried auto completing for the function.

**Comment by agentgt** [comment]
BTW it seems like:

```java
 public JWT decode(String encodedJWT, Map<String, Verifier> verifiers)
```

should be 

```java
 public JWT decode(String encodedJWT, Function<String, Verifier> verifiers)
```

**Comment by voidmain** [comment]
That's another signature we could support. The current method allows you to provide the mapping between the `Verifier` and the `kid`. Feel free to open a feature request to support the `Function` implementation as well.
