### ISSUE TITLE
"The JWT could not be de-serialized."

### ISSUE THREAD

**Issue by salami** [FusionAuth/fusionauth-jwt#48]
This is for a kotlin-based Android project.

I'm calling `Mapper.deserialize(bytes, JSONWebKey::class.java)` and it works completely fine on my dev build from android studio, but in a prod release it throws an InvalidJWTException error with the message "The JWT could not be de-serialized."

Any idea what the issue is? Do I need to add some proguard rules?

**Comment by mooreds** [comment]
What versions of java are you targeting in each environment?

**Comment by salami** [comment]
Java 1.8 for both. I'm going to try a build now with the minify/obfuscate stuff taken out.

**Comment by robotdan** [comment]
Possibly related:
- https://github.com/FusionAuth/fusionauth-jwt/issues/42

No idea if this library will work in Dalvik or Android runtime (ART).

**Comment by salami** [comment]
Ok it's working for me without the minify/obfuscate stuff.

I don't know much about proguard rules but I'll try to investigate when I get some time. My app is only being pushed for internal testing right now so low urgency.
