### ISSUE TITLE
Need Ability to Extend `Header` class

### ISSUE THREAD

**Issue by mdemille** [FusionAuth/fusionauth-jwt#52]
I am using this library in support of the STIR/SHAKEN protocol in telecom. The RFC specifies that the `Header` of a JWT [must have its keys in lexicographical order](https://www.rfc-editor.org/rfc/rfc8225.html#section-9). 

The `JWTEncoder` class manually builds a header object and then allows a `Consumer<Header>` to customize it. I would like to be able to subclass the `Header` class so that I have tighter/easier control over the fields in that class, and still have it used by the encoder.

**Comment by robotdan** [comment]
Released. Available in `5.3.0`.

**Comment by mdemille** [comment]
Thank you!
