### ISSUE TITLE
JDK 9+ support

### ISSUE THREAD

**Issue by skjolber** [FusionAuth/fusionauth-jwt#8]
Please add a module descriptor.

**Comment by robotdan** [comment]
Can you provide some additional detail to what you're looking for and the use case? Thanks!

**Comment by skjolber** [comment]
Well an Automatic module name would be a good first step, then later a real module info (guess using moditect-maven-plugin is the fastest). Use-case: Java 11 application with modules.

**Comment by robotdan** [comment]
Will this help you out? See commit https://github.com/FusionAuth/fusionauth-jwt/commit/82033d02a4e059f1aa4c361255cf87ef494a0c87


I haven't dealt much yet with modules, so please share any feedback you have.

**Comment by skjolber** [comment]
See https://github.com/FusionAuth/fusionauth-jwt/pull/10 for a suggestion.

**Comment by robotdan** [comment]
I removed the `module-info.java` file for now, JDK8 won't compile this, so I'll have to build two artifacts from this project one for Java8, and another for Java9 and only include this when compiling Java9.

**Comment by skjolber** [comment]
To stay on 8, use the moditect plugin:

```xml
<plugin>
    <groupId>org.moditect</groupId>
    <artifactId>moditect-maven-plugin</artifactId>
    <version>1.0.0.Beta2</version>
    <executions>
        <execution>
            <id>add-module-infos</id>
            <phase>package</phase>
            <goals>
                <goal>add-module-info</goal>
            </goals>
            <configuration>
                <jvmVersion>${java.module.version}</jvmVersion>
                <overwriteExistingFiles>true</overwriteExistingFiles>
                <module>
                    <moduleInfoFile>src/main/moditech/module-info.java</moduleInfoFile>
                </module>
            </configuration>
        </execution>
    </executions>
</plugin>
```

with the module-info in a seperate source folder.

**Comment by robotdan** [comment]
Thanks @skjolber for the help! Added it back under commit https://github.com/FusionAuth/fusionauth-jwt/commit/3a45068ea7f124fea650cca305e64702726b9497

**Comment by skjolber** [comment]
@robotdan and remember to import jackson modules (read: your module uses the jackson module).

**Comment by skjolber** [comment]
https://github.com/FusionAuth/fusionauth-jwt/pull/10/files#diff-9b957a8dd84164d8cb3b155d2c886290R14-R16

**Comment by robotdan** [comment]
Thanks @skjolber sorry - totally forgot / missed your PR with all of this in it already. Thanks for the help!
