### ISSUE TITLE
Benchmark / performance testing

### ISSUE THREAD

**Issue by skjolber** [FusionAuth/fusionauth-jwt#9]
Hi, do you have an existing benchmark of JWT token decoding? If not [this](https://github.com/skjolber/java-jwt-benchmark) might be interesting.

**Comment by robotdan** [comment]
We have done some internal testing, but nothing official that we've posted. That is interesting, I'll take a look.

**Comment by skjolber** [comment]
I did not need to modify the other frameworks, it is just a matter of producing some code for

**Comment by skjolber** [comment]
@robotdan See [PR](https://github.com/skjolber/java-jwt-benchmark/pull/1).

**Comment by skjolber** [comment]
Initial run seems to indicate that you're the fastest so far, by something like 5%.

**Comment by robotdan** [comment]
Awesome.. sorry, been swamped. I'll try to take a look at your code shortly and see if I can make any recommendations for improvement.

**Comment by skjolber** [comment]
So no comments / changes then? I'll finish up on the 8th of November at the latest.

**Comment by robotdan** [comment]
Hi @skjolber added a few comments in your PR, nothing super important, but I left a few suggestions. 

Thanks.

**Comment by skjolber** [comment]
Thank for the feedback. According to the benchmarks, you are the new fastest kid on the block. Well done. See [project page](https://github.com/skjolber/java-jwt-benchmark) for a summary, or [JMH results](https://skjolber.github.io/java-jwt-benchmark/jmh_v1.2.0/index.html).
